title: Podcast short stories and music for anxiety
theme: jekyll-theme-midnight
collections:
  anxiety_meditations:
    output: true

defaults:
  - scope:
      type: "anxiety_meditations"
    values:
      layout: anxiety_meditations
